# Generated by Django 5.1 on 2024-08-22 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_episode_serie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='serie',
        ),
    ]
