# Generated by Django 5.1 on 2024-08-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_episode_serie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='production_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='category',
            field=models.ManyToManyField(related_name='Series', to='base.category'),
        ),
    ]
