# Generated by Django 5.1 on 2024-08-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_actor_category_episode_rating_serie_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='production_date',
            field=models.IntegerField(null=True),
        ),
    ]
