# Generated by Django 5.1 on 2024-08-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_serie_production_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='img',
            field=models.URLField(null=True),
        ),
    ]
